FROM python:3.8



WORKDIR /app

COPY requirements.txt /app
RUN pip install -r requirements.txt

EXPOSE 5000

COPY ./ /app
ENV FLASK_APP=app
ENV FLASK_ENV=development
ENV SQLALCHEMY_DATABASE_URI=mysql+mysqlconnector://root:root@db:3306/citiesData
ENV SECRET_KEY=ZHANG
CMD ["python", "wsgi.py"]